export const top100Films = [
    { time: '09:00 AM', }, { time: '09:15 AM' },
    { time: '09:30 AM', },]

export const Tabs = [{ text: 'Patient Information' },
{ text: 'Intake Assessment' }, { text: 'Insurance Information' },
{ text: 'Other Contacts' }, { text: 'Telephone Intake' }];
export const txtareas = [{
    label: 'Patient Calender Notes', required: true,
    name: 'patient_calender_notes',
    id: 'patient_calender_notes'
},
{
    label: 'Miscalleneaous Notes', name: 'miscalleneaous_notes',
    id: 'miscalleneaous_notes',
    required: true
}]

export const arr = [
    {
        label: 'Department',
        id: 'department',
        name: 'department',
        grid: 1,
        type: 'select',
        required: true,
        menuitems: ['a']
    },
    {
        label: 'Providers / Programs',
        grid: 2,
        id: 'providers_programs',
        name: 'providers_programs',
        type: 'select',
        required: true,
        menuitems: ['a']
    },
    {
        label: '',
        grid: 3,
        type: 'empty',
    },
    {
        label: '',
        grid: 4,
        type: 'empty',
    },
    {
        label: 'Select a Clinician',
        type: 'select',
        grid: 1,
        name: 'single_clinician',
        id: 'single_clinician',
        required: true,
        menuitems: ['a', 'b']
    },
    {
        label: 'Select Multiple  Clinician',
        type: 'select',
        grid: 2,
        name: 'multiple_clinician',
        id: 'multiple_clinician',
        required: true,
        menuitems: ['c', 'd']
    }, {
        label: '',
        grid: 3,
        type: 'empty',
    }, {
        placeholder: 'Assign Provider(s)',
        type: 'button',
        grid: 4,
    },]

export const PatientInfoCollapse = [
    {
        label: "First Name",
        required: true,
        id: "first_name",
        type: "text",
        grid: 1,
        placeholder: 'First Name',
        name: "first_name",
    }, {
        label: "Country",
        required: true,
        id: "country",
        type: "text",
        grid: 1,
        placeholder: 'Country',
        name: "country",
    }, {
        label: 'Address',
        required: true,
        id: "address",
        type: "text",
        grid: 1,
        placeholder: 'Address',
        name: "address",
    }, {
        label: "Patient Status",
        required: true,
        id: "patient_status",
        type: "radio",
        placeholder: 'Patient Status',
        grid: 1,
        name: "patient_status",
        radios: ['Active', 'Inactive', 'Pending']
    }, {
        label: "Last Name",
        required: false,
        id: "last_name",
        type: "text",
        grid: 2,
        placeholder: 'Last Name',
        name: "last_name",
    }, {
        label: "City, State",
        required: false,
        grid: 2,
        id: "city_state",
        type: "text",
        placeholder: 'City, State',
        name: "city_state",
    }, {
        label: 'Email',
        required: true,
        id: "email",
        grid: 2,
        type: "text",
        placeholder: 'Email',
        name: "email",
    }, {
        label: "Appoinment Reminder",
        required: true,
        id: "appoinment_reminder",
        type: "checkbox",
        grid: 2,
        placeholder: 'Multiple Birth',
        name: "appoinment_reminder",
    }, {
        label: "Date Of Birth",
        required: false,
        id: "date_of_birth",
        grid: 3,
        type: "date",
        placeholder: 'Date Of Birth',
        name: "date_of_birth",
    },
    {
        label: "Gender",
        required: false,
        id: "gender",
        type: "select",
        menuitems: ['a', 'b', 'c'],
        placeholder: 'Gender',
        grid: 3,
        name: "gender",
    }, {
        label: 'Race',
        required: true,
        id: "race",
        type: "select",
        menuitems: ['a', 'b', 'c'],
        grid: 3,
        placeholder: 'Race',
        name: "race",
    },
    {
        label: "Available Providers/ Programs",
        required: true,
        id: "available_providers",
        grid: 3,
        type: "select",
        menuitems: ['a', 'b', 'c'],
        placeholder: "Available Providers/ Programs",
        name: "available_providers",
    }, {
        label: 'Mobile Nmuber',
        required: true,
        id: "mobile_number",
        type: "text",
        placeholder: 'Mobile Nmuber',
        name: "mobile_number",
        grid: 4,
    }, {
        label: 'Marital Status',
        required: true,
        id: "marital_status",
        type: "select",
        placeholder: 'Marital Status',
        grid: 4,
        menuitems: ['a', 'b'],
        name: "marital_status",
    },
    {
        label: 'Patient ID',
        required: true,
        id: "patient_id",
        type: "btn_text",
        grid: 4,
        placeholder: 'Generate',
        name: "patient_id",
    },
    {
        id: "continue",
        name: "continue",
        type: "button",
        grid: 4,
        placeholder: 'Continue',
    }
]

export const MoreInfoCollapse = [{
    label: 'Refer to Patient as',
    required: true,
    id: "refer_to_patient",
    type: "text",
    grid: 1,
    placeholder: 'Refer to Patient as ',
    name: "refer_to_patient",
},
{
    label: 'Ethinicity',
    required: true,
    id: "ethinicity",
    grid: 1,
    type: "select",
    menuitems: ['aEthinicity'],
    placeholder: 'Ethinicity',
    name: "ethinicity",
}, {
    label: 'Religion',
    grid: 1,
    menuitems: ['Religion'],
    required: true,
    id: "religion",
    type: "select",
    placeholder: 'Religion',
    name: "religion",
},
{
    label: 'Preferred Language',
    required: true,
    grid: 1,
    id: "preferred_language",
    type: "select",
    menuitems: ['prefered laniugae'],
    placeholder: 'Preferred Language',
    name: "preferred_language",
}, {
    label: 'Sexual Orientation',
    required: true,
    grid: 1,
    id: "sexual_orientation",
    type: "select",
    menuitems: ['sexual orientation'],
    placeholder: 'Sexual Orientation',
    name: "sexual_orientation",
}, {
    label: 'All Patient ID',
    required: true,
    grid: 2,
    id: "all_patient_id",
    type: "text",
    placeholder: 'All Patient ID',
    name: "all_patient_id",
},
{
    label: 'Ethinicity 2',
    required: true,
    grid: 2,
    id: "ethinicity2",
    type: "select",
    menuitems: ['ethinicity'],
    placeholder: 'Ethinicity',
    name: "ethinicity2",
}, {
    label: 'Birth Order',
    grid: 2,
    menuitems: ['birth order'],
    required: true,
    id: "birth_order",
    type: "select",
    placeholder: 'birth Order',
    name: "birth_order",
},
{
    label: 'Romm',
    required: true,
    id: "romm",
    grid: 2,
    type: "text",
    placeholder: 'Romm',
    name: "romm",
}, {
    label: 'Veteran',
    grid: 2,
    required: true,
    id: "Veteran",
    type: "radio",
    radios: ['yes', 'No'],
    placeholder: 'Veteran',
    name: "Veteran",
},
{
    label: 'SSN#:',
    required: true,
    id: "ssn",
    grid: 3,
    type: "text",
    placeholder: 'SSN #',
    name: "ssn",
},
{
    label: 'Disability',
    required: true,
    grid: 3,
    id: "disability",
    type: "select",
    menuitems: ['disability'],
    placeholder: 'disability',
    name: "disability",
}, {
    label: 'Family Size',
    grid: 3,
    menuitems: ['Family Size'],
    required: true,
    id: "family_size",
    type: "select",
    placeholder: 'Family Size',
    name: "family_size",
},
{
    label: 'Maiden/ Other Name',
    required: true,
    id: "maiden_other_name",
    grid: 3,
    type: "text",
    placeholder: 'Maiden/ Other Name',
    name: "maiden_other_name",
},
{
    label: " ",
    required: true,
    id: "multiple_birth",
    type: "checkbox",
    placeholder: 'Multiple Birth',
    name: "multiple_birth",
    grid: 3,
},
{
    label: 'Release Of Info',
    required: true,
    id: "release_of_info",
    type: "select",
    grid: 4,
    menuitems: ['Release Of Info'],
    placeholder: 'Release Of Info',
    name: "release_of_info",
},
{
    label: 'Employment Status',
    required: true,
    id: "employment_status",
    grid: 4,
    type: "select",
    menuitems: ['employ status'],
    placeholder: 'Employment Status',
    name: "employment_status",
},
{
    label: 'Alt. Address',
    required: true,
    id: "alt_address",
    grid: 4,
    type: "text",
    placeholder: 'Alt. Address',
    name: "alt_address",
}, {
    label: 'Email 2',
    required: true,
    id: "email2",
    type: "text",
    grid: 4,
    placeholder: 'Email 2',
    name: "email2",
},
{
    label: 'Native American ?',
    required: true,
    id: "native_american",
    type: "radio",
    grid: 4,
    radios: ['Yes', 'No'],
    placeholder: 'Native American ',
    name: "native_american",
}]

// Intake asseesmtnt

export const IntakeAssesmentFirstCollapse = [
    {
        label: 'Date Of Admission Form',
        required: true,
        id: "date_of_admission_form",
        type: "date",
        grid: 1,
        placeholder: 'Date Of Admission Form',
        name: "date_of_admission_form",
    }, {
        label: 'Date Of Current Illness',
        required: true,
        grid: 1,
        id: "date_of_current_illness",
        type: "date",
        placeholder: 'Date Of Current Illness',
        name: "date_of_current_illness",
    }, {
        label: 'Is Treatment Previously?',
        grid: 1,
        required: true,
        id: "is_treat_preiously",
        type: "radio",
        radios: ['Yes', 'No'],
        placeholder: 'Is Treatment Previously?',
        name: "is_treat_preiously",
    }, {
        label: 'Condition Related To Employment',
        required: true,
        id: "condition_related_to_employ",
        grid: 1,
        type: "radio",
        placeholder: 'Condition Related To Employment',
        radios: ['Yes', 'No'],
        name: "condition_related_to_employ",
    }, {
        label: 'Premliminary Case',
        required: true,
        id: "preliminary_case",
        type: "select",
        menuitems: ['a'],
        grid: 1,
        placeholder: 'Premliminary Case',
        name: "preliminary_case",
    },
    {
        label: 'To',
        required: true,
        id: "to",
        type: "date",
        placeholder: 'To',
        name: "to",
        grid: 2,
    }, {
        label: 'Date Of Similar Illness',
        required: true,
        id: "date_of_similar_illness",
        type: "date",
        grid: 2,
        placeholder: 'Date Of Similar Illness',
        name: "date_of_similar_illness",
    }, {
        label: 'If Yes, Where',
        required: true,
        grid: 2,
        id: "if_yes_where",
        type: "text",
        placeholder: 'If Yes, Where',
        name: "if_yes_where",
    }, {
        label: 'Condition Related To Auto Accident',
        required: true,
        grid: 2,
        id: "condition_related_to_auto_accident",
        type: "radio",
        placeholder: 'Condition Related To Employment',
        radios: ['Yes', 'No'],
        name: "condition_related_to_auto_accident",
    }, {
        type: "button",
        grid: 2,
        placeholder: 'Save',
    },
    {
        grid: 3,
        label: 'Date Of Unable to work',
        required: true,
        id: "date_of_unable_to_work",
        type: "date",
        placeholder: 'Date Of Unable to work',
        name: "date_of_unable_to_work",
    }, {
        label: 'Admitting DX',
        required: true,
        id: "admitting_dx",
        grid: 3,
        type: "text",
        placeholder: 'Admitting DX',
        name: "admitting_dx",
    },
    {
        label: 'Past Disease History',
        required: true,
        grid: 3,
        id: "past_disease_history",
        type: "select",
        menuitems: ['a'],
        placeholder: 'Past Disease History',
        name: "past_disease_history",
    }, {
        label: 'Condition Related To Other Accident',
        required: true,
        id: "condition_related_to_other_accident",
        type: "radio",
        grid: 3,
        placeholder: 'Condition Related To other Accident',
        radios: ['Yes', 'No'],
        name: "condition_related_to_other_accident",
    },
    {
        label: 'To',
        required: true,
        grid: 4,
        id: "to_last",
        type: "date",
        placeholder: 'To',
        name: "to_last",
    }, {
        label: 'Major symptoms',
        required: true,
        id: "major_symptoms",
        type: "select",
        menuitems: ['a'],
        grid: 4,
        placeholder: 'Major Symptoms',
        name: "major_symptoms",
    },
    { label: '', grid: 4, },
    {
        label: 'State Of Accident',
        required: true,
        id: "state_of_accident",
        grid: 4,
        type: "text",
        placeholder: 'State Of Accident',
        name: "state_of_accident",
    }
]



export const firstCollapse = [{
    label: 'Insurance',
    required: true,
    id: "insurance",
    grid: 1,
    type: "select",
    placeholder: 'Insurance',
    menuitems: ['a'],
    name: "insurance",
},
{
    label: 'Group',
    required: true,
    id: "group",
    grid: 1,
    type: "text",
    placeholder: 'Major Symptoms',
    name: "group",
},

{
    label: 'Member Id / Policy #',
    required: true,
    id: "member_id_policy",
    type: "text",
    grid: 2,
    placeholder: 'Member Id / Policy #',
    name: "member_id_policy",
}, {
    label: "Patient RelationShip To Insured",
    required: true,
    id: "patient_relationship",
    type: "radio",
    grid: 2,
    placeholder: 'Patient Status',
    name: "patient_relationship",
    radios: ['Self', 'Spouse', 'Child', 'Other']
},

{
    label: 'Start Date',
    required: true,
    id: "start_date",
    type: "date",
    grid: 3,
    placeholder: 'Start Date',
    name: "start_date",
},
{ label: '', grid: 3 },
{
    label: 'Suspended Date',
    required: true,
    id: "suspended_date",
    type: "date",
    grid: 4,
    placeholder: 'suspended Date',
    name: "suspended_date",
},
{
    required: true,
    type: "button",
    grid: 4,
    placeholder: 'Continue',
}]

export const secondCollapse = [{
    label: 'First Name',
    required: true,
    id: "first_name",
    grid: 1,
    type: "text",
    placeholder: 'First Name',
    name: "first_name",
},
{
    label: 'SSN#',
    required: true,
    id: "ssn",
    grid: 1,
    type: "text",
    placeholder: 'SSN',
    name: "ssn",
},

{
    label: 'State',
    required: true,
    id: "state",
    type: "text",
    grid: 1,
    placeholder: 'State',
    name: "state",
},
{
    label: "Last Name",
    required: true,
    id: "last_name",
    type: "text",
    grid: 2,
    placeholder: 'last Name',
    name: "last_name",
},

{
    label: "Employer",
    required: true,
    id: "employer",
    type: "text",
    grid: 2,
    placeholder: 'Employer',
    name: "employer",
},
{
    label: "Zip",
    required: true,
    id: "zip",
    type: 'text',
    grid: 2,
    placeholder: 'Zip',
    name: "zip",
},

{
    label: "Address",
    required: true,
    id: "address",
    type: 'text',
    grid: 3,
    placeholder: 'Address',
    name: "address",
},
{
    label: "DOB",
    required: true,
    id: "dob",
    type: 'date',
    grid: 3,
    name: "dob",
},
{
    label: "Gender",
    required: true,
    id: "gender",
    type: 'select',
    grid: 3,
    placeholder: "Gender",
    menuitems: ['male', 'female'],
    name: "gender",
},
{
    label: "Phone",
    required: true,
    id: "phone",
    type: 'text',
    grid: 4,
    name: "phone",
},
{
    label: "City",
    required: true,
    id: "text",
    type: 'text',
    grid: 4,
    name: "city",
},

{
    required: true,
    type: "button",
    grid: 4,
    placeholder: 'Continue',
},]

export const thirdCollapse = [{
    label: 'Name',
    required: true,
    id: "name",
    grid: 1,
    type: "select",
    menuitems: ['a'],
    placeholder: 'Name',
    name: "name",
},
{
    label: 'Eligibility Id',
    required: true,
    id: "eligibility_id",
    grid: 1,
    type: "text",
    placeholder: 'Eligibility Id',
    name: "eligibility_id",
},
{
    label: 'State',
    required: true,
    id: "state",
    type: "text",
    grid: 1,
    placeholder: 'State',
    name: "state",
},
{
    label: "Use Alt. Facility - NPI",
    required: true,
    id: "use_alt_facility",
    type: "select",
    grid: 1,
    menuitems: ['a'],
    placeholder: 'Use Alt. Facility - NPI',
    name: "use_alt_facility",
},
{
    label: "Payer ID",
    required: true,
    id: "payer_id",
    type: "text",
    grid: 2,
    placeholder: 'Payer ID',
    name: "payer_id",
},
{
    label: "Insurance Type",
    required: true,
    id: "insurance_type",
    type: 'select',
    grid: 2,
    menuitems: ['a'],
    placeholder: "Insurance Type",
    name: "insurance_type",
},
{
    label: "ZIP",
    required: true,
    id: "zip",
    type: 'text',
    grid: 2,
    placeholder: 'Zip',
    name: "zip",
},
{
    label: "ID Qualifier 24i",
    required: true,
    id: "id_qualifier_24i",
    type: 'text',
    grid: 2,
    name: "id_qualifier_24i",
},
{
    label: "Address",
    required: true,
    id: "address",
    type: 'text',
    grid: 3,
    placeholder: "Address",
    name: "address",
},
{
    label: "Insurance Type Other",
    required: true,
    id: "insurance_type_other",
    type: 'select',
    grid: 3,
    menuitems: ['a', 'b'],
    name: "insurance_type_other",
},
{
    label: "Submission Method",
    required: true,
    id: "submission_method",
    type: 'select',
    menuitems: ['a', 'b'],
    grid: 3,
    name: "submission_method",
},
{
    label: "Use Alt. Provider - Text ID",
    required: true,
    id: "use_alt_provider_text",
    type: 'select',
    menuitems: ['a', 'b'],
    grid: 3,
    name: "use_alt_provider_text",
},
{
    label: "Phone",
    required: true,
    id: "phone",
    type: 'text',
    grid: 4,
    placeholder: "Phone",
    name: "phone",
},
{
    label: "City",
    required: true,
    id: "city",
    type: 'text',
    grid: 4,
    placeholder: "City",
    name: "city",
},
{
    label: "Alt. Payer ID",
    required: true,
    id: "alt_payer_id",
    type: 'text',
    grid: 4,
    placeholder: "Alt. Payer ID",
    name: "alt_payer_id",
},
{
    required: true,
    id: "use_alt",
    type: 'checkbox',
    grid: 4,
    placeholder: "Use Alt. provider Id",
    name: "use_alt",
},
{
    required: true,
    type: "button",
    grid: 4,
    placeholder: 'Continue',
}]


export const fourthCollapse = [{
    label: 'Discount %',
    required: true,
    id: "discount",
    grid: 1,
    type: "text",
    placeholder: 'Discount %',
    name: "discount",
},
{
    label: 'MCM Auth Required.',
    required: true,
    id: "mcm_auth_required",
    grid: 1,
    type: "radio",
    radios: ['Yes', 'no'],
    placeholder: 'MCM Auth Required.',
    name: "mcm_auth_required",
},
{
    required: true,
    id: "freeze_account",
    type: "checkbox",
    grid: 2,
    placeholder: 'Freeze Account ',
    name: "freeze_account",
},
{
    label: 'Discount %',
    required: true,
    id: "discount_two",
    type: "text",
    grid: 2,
    placeholder: 'Discount %',
    name: "discount_two",
}]


export const Benefits = [{
    label: 'Insurance',
    required: true,
    id: "insurance",
    type: "select",
    menuitems: ['a'],
    grid: 1,
    placeholder: 'Insurance',
    name: "insurance",
}, {
    label: 'In network',
    required: true,
    id: "in_network",
    type: "date",
    grid: 1,
    placeholder: 'In Network',
    name: "in_network",
}, {
    label: 'Earlier Disorder Covered?',
    required: true,
    id: "earlier_discount_covered",
    type: "radio",
    radios: ['Yes', 'No'],
    grid: 1,
    placeholder: 'Earlier Disorder Covered?',
    name: "earlier_discount_covered",
}, {
    label: 'Rct (% Covered / days allowed per year)',
    required: true,
    id: "rct_covered_days_allowed",
    type: "text",
    grid: 1,
    placeholder: 'Rct (% Covered / days allowed per year)',
    name: "rct_covered_days_allowed",
}, {
    label: 'Does Partial come out of RTC or IP benefits?',
    required: true,
    id: "does_partial_come_out",
    type: "text",
    grid: 1,
    placeholder: 'Does Partial come out of RTC or IP benefits?',
    name: "does_partial_come_out",
}, {
    label: 'IOP(% covered/days allowed per year)',
    required: true,
    id: "iop_allowed_covered",
    type: "text",
    grid: 1,
    placeholder: 'IOP(% covered/days allowed per year)',
    name: "iop_allowed_covered",
}, {
    label: 'Mental Health (Party Disanogis)',
    required: true,
    id: "mental_health",
    type: "text",
    grid: 1,
    placeholder: 'Mental Health (Party Disanogis)',
    name: "mental_health",
}, {
    label: 'Pre Certification Required',
    required: true,
    id: "pre_certification",
    type: "radio",
    grid: 1,
    placeholder: 'Pre Certification Required',
    radios: ['Yes', 'No'],
    name: "pre_certification",
},
{
    label: 'Deductible (Individual)',
    required: true,
    id: "deductible_individual",
    type: "text",
    grid: 1,
    placeholder: 'Deductible (Individual)',
    name: "deductible_individual",
}, {
    label: 'Deductible (Family)',
    required: true,
    id: "deductible_family",
    type: "text",
    grid: 1,
    placeholder: 'Deductible (Family)',
    name: "deductible_family",
}, {
    label: 'Out Of Pocket Maximum',
    required: true,
    id: "out_of_pocket",
    type: "text",
    grid: 1,
    placeholder: 'Out Of Pocket Maximum',
    name: "out_of_pocket",
}, {
    label: 'Lifetime Maximum',
    required: true,
    id: "lifetime_max",
    type: "text",
    grid: 1,
    placeholder: 'Lifetime Maximum',
    name: "lifetime_max",
}, {
    label: 'Out Of State Treatment Covered?',
    required: true,
    id: "out_of_state",
    type: "text",
    grid: 1,
    placeholder: 'Out Of State Treatment Covered?',
    name: "out_of_state",
}, {
    label: 'Assigned Of Benefits',
    required: true,
    id: "assigned_of_benefits",
    type: "select",
    menuitems: ['a'],
    grid: 2,
    placeholder: 'Assigned Of Benefits',
    name: "assigned_of_benefits",
}, {
    label: 'Out Network',
    required: true,
    id: "out_network",
    type: "date",
    grid: 2,
    placeholder: 'Out Network',
    name: "out_network",
    label: '',
}, {
    required: true,
    id: "eating_disorder_right",
    type: "radio",
    label: '',
    grid: 2,
    radios: ['yes', 'No'],
    name: "eating_disorder_right",
}, {
    required: true,
    id: "rct_covered_right",
    type: "text",
    label: '',
    grid: 2,
    name: "rct_covered_right",
}, {
    required: true,
    id: "does_partial_right",
    type: "text",
    grid: 2,
    label: '',
    name: "does_partial_right",
}, {
    required: true,
    id: "iop_covered_right",
    type: "text",
    grid: 2,
    label: '',
    name: "iop_covered_right",
}, {
    required: true,
    id: "mental_health_right",
    type: "text",
    grid: 2,
    label: '',
    name: "mental_health_right",
}, {
    required: true,
    id: "pre_certification_right",
    type: "radio",
    radios: ['Yes', "No"],
    label: '',
    grid: 2,
    name: "pre_certification_right",
}, {
    required: true,
    label: '',
    id: "deductible_ind_right",
    type: "text",
    grid: 2,
    name: "deductible_ind_right",
}, {
    required: true,
    id: "deductible_family_right",
    type: "text",
    grid: 2,
    name: "deductible_family_right",
    label: '',
}, {
    required: true,
    id: "outpocket_right",
    type: "text",
    grid: 2,
    label: '',
    name: "outpocket_right",
}, {
    required: true,
    id: "lifetime_max_right",
    type: "text",
    grid: 2,
    label: '',
    name: "lifetime_max_right",
}, {
    required: true,
    id: "outof_state_right",
    type: "radio",
    label: '',
    radios: ['Yes', 'No'],
    grid: 2,
    name: "outof_state_right",
}]

export const benefitsTwo = [{
    required: true,
    type: 'text',
    label: 'InPatient Deductible / # days',
    grid: 1,
    name: 'inpatient_deductible',
    id: 'inpatient_deductible',
}, {
    required: true,
    type: 'text',
    label: 'Residential Deductible / # Days',
    placeholder: 'Residential Deductible / # Days',
    name: 'residential_deductible',
    id: 'residential_deductible',
    grid: 1
}, {
    required: true,
    type: 'text',
    label: 'PHP Deductible / # days',
    grid: 1,
    name: 'php_deductible',
    id: 'php_deductible',
}, {
    required: true,
    label: '',
    grid: 2,
    type: 'text',
    name: 'inpatient_deductible_two',
    id: 'inpatient_deductible_two',
}, {
    required: true,
    label: '',
    grid: 2,
    name: 'residential_deductible_two',
    id: 'residential_deductible_two',
    type: 'text',
}, {
    required: true,
    label: '',
    grid: 2,
    name: 'php_deductible_two',
    type: 'text',
    id: 'php_deductible_two',
}, {
    required: true,
    label: '',
    type: 'text',
    grid: 3,
    name: 'inpatient_deductible_three',
    id: 'inpatient_deductible_three',

}, {
    required: true,
    label: '',
    type: 'text',
    grid: 3,
    name: 'residential_deductible_three',
    id: 'residential_deductible_three',
}, {
    required: true,
    label: '',
    grid: 3,
    name: 'php_deductible_three',
    id: 'php_deductible_three',
    type: 'text',

}, {
    required: true,
    label: '',
    grid: 4,
    name: 'inpatient_deductible_four',
    id: 'inpatient_deductible_four',
    type: 'text',
}, {
    required: true,
    label: '',
    grid: 4,
    type: 'text',
    name: 'residential_deductible_four',
    id: 'residential_deductible_four',
}, {
    required: true,
    label: '',
    grid: 4,
    name: 'php_deductible_four',
    type: 'text',
    id: 'php_deductible_four',
}]

export const Payments = [{
    required: true,
    label: 'Copay',
    grid: 1,
    type: 'text',
    placeholder: 'Copay',
    name: 'copay',
    id: 'copay',
}, {
    required: true,
    label: 'Patient Responsibility',
    grid: 1,
    type: 'text',
    placeholder: 'Patient Responsibility',
    name: 'patient_responsibility',
    id: 'patient_responsibility',
}, {
    required: true,
    label: 'Allowed Amount',
    grid: 2,
    type: 'text',
    placeholder: 'Allowed Amount',
    name: 'allow_amount',
    id: 'allow_amount',
}, {
    required: true,
    label: 'Deductible',
    grid: 2,
    type: 'text',
    name: 'deductible',
    id: 'deductible',
}, {
    required: true,
    label: 'Contractual Adjustment',
    grid: 3,
    placeholder: 'Contractual Adjustment',
    type: 'text',
    name: 'contractual_adjust',
    id: 'contractual_adjust',
}, {
    required: true,
    label: 'co-Insurance (%)',
    placeholder: 'co-Insurance (%)',
    grid: 3,
    type: 'text',
    name: 'co_insurance',
    id: 'co_insurance',
}, {
    required: true,
    label: 'Insurance Payment',
    placeholder: 'Insurance Payment',
    grid: 4,
    type: 'text',
    name: 'insurance_payment',
    id: 'insurance_payment',
}, {
    required: true,
    placeholder: 'Continue',
    grid: 4,
    type: 'button',
}]

export const Eligibility = [
    {
        required: true,
        placeholder: 'Check Eligibility For selected Payer',
        grid: 1,
        type: 'button',
    },
    {
        required: true,
        label: 'Copay',
        placeholder: 'Copay',
        grid: 1,
        type: 'text',
        name: 'copay_in_one',
        id: 'copay_in_one',
    }, {
        required: true,
        label: 'Copay',
        placeholder: 'Copay',
        grid: 1,
        type: 'text',
        name: 'copay_out_one',
        id: 'copay_out_one',
    }, {
        required: true,
        label: 'Date & Time Checked',
        placeholder: 'Date & Time Checked',
        grid: 2,
        type: 'text',
        name: 'date_time_checked',
        id: 'date_time_checked',
    }, {
        required: true,
        label: 'Deductable',
        placeholder: 'Deductable',
        grid: 2,
        type: 'text',
        name: 'deductable_in',
        id: 'deductable_in'
    }, {
        required: true,
        label: 'Deductable',
        placeholder: 'Deductable',
        grid: 2,
        type: 'text',
        name: 'deductable_out',
        id: 'deductable_out',
    }, {
        required: true,
        label: 'Date & Time Checked',
        placeholder: 'Date & Time Checked',
        grid: 3,
        type: 'text',
        name: 'date_time_checked_two',
        id: 'date_time_checked_two',
    }, {
        required: true,
        label: 'Co Insurance',
        placeholder: 'Co Insurance',
        grid: 3,
        type: 'text',
        name: 'co_insurance_in',
        id: 'co_insurance_in',
    }, {
        required: true,
        label: 'Co Insurance',
        placeholder: 'Co Insurance',
        grid: 3,
        type: 'text',
        name: 'co_insurance_out',
        id: 'co_insurance_out',
    },
    {
        label: '',
        grid: 4,
        type: 'empty',
    },
    {
        required: true,
        label: 'Out Of Pocket Maximum',
        placeholder: 'Out Of Pocket Maximum',
        grid: 4,
        type: 'text',
        name: 'out_of_pocketmax_one',
        id: 'out_of_pocketmax_one',
    }, {
        required: true,
        label: 'Out Of Pocket Maximum',
        placeholder: 'Out Of Pocket Maximum',
        grid: 4,
        type: 'text',
        name: 'out_of_pocketmax_two',
        id: 'out_of_pocketmax_two',
    },
]

export const MedicalCOntacts = [{
    required: true,
    label: 'Primary Care Person',
    placeholder: 'Primary Care Person',
    grid: 1,
    type: 'select',
    menuitems: ['a'],
    name: 'primary_care_person',
    id: 'primary_care_person',
}, {
    required: true,
    label: 'OutPatient Psychiathrapist',
    placeholder: 'OutPatient Psychiathrapist',
    grid: 1,
    type: 'select',
    menuitems: ['a'],
    name: 'out_patient_psychithrapist',
    id: 'out_patient_psychithrapist',
}, {
    required: true,
    label: 'Out Patient Therapist',
    placeholder: 'Out Patient Therapist',
    grid: 1,
    type: 'select',
    menuitems: ['a'],
    name: 'out_patient_therpist',
    id: 'out_patient_therpist',
}, {
    required: true,
    label: 'School Contact',
    placeholder: 'School Contact',
    grid: 1,
    menuitems: ['a'],
    type: 'select',
    name: 'school_contact',
    id: 'school_contact',
}, {
    required: true,
    label: 'SASS Worker',
    placeholder: 'SASS Worker',
    grid: 1,
    type: 'select',
    menuitems: ['a'],
    name: 'sass_worker',
    id: 'sass_worker',
}, {
    required: true,
    label: 'Pharmacy',
    placeholder: 'Pharmacy',
    grid: 1,
    type: 'select',
    menuitems: ['a'],
    name: 'pharmacy',
    id: 'pharmacy',
},
{
    required: true,
    label: 'Phone',
    placeholder: 'Phone',
    grid: 2,
    type: 'text',
    name: 'phone',
    id: 'phone',
},
{
    required: true,
    label: 'Phone',
    placeholder: 'Phone',
    grid: 2,
    type: 'text',
    name: 'phone_one',
    id: 'phone_one',
}, {
    required: true,
    label: 'Phone',
    placeholder: 'Phone',
    grid: 2,
    type: 'text',
    name: 'phone_two',
    id: 'phone_two',
}, {
    required: true,
    label: 'Phone',
    placeholder: 'Phone',
    grid: 2,
    type: 'text',
    name: 'phone_three',
    id: 'phone_three',
}, {
    required: true,
    label: 'Phone',
    placeholder: 'Phone',
    grid: 2,
    type: 'text',
    name: 'phone_four',
    id: 'phone_four',
},
{
    required: true,
    label: 'Phone',
    placeholder: 'Phone',
    grid: 2,
    type: 'text',
    name: 'phone_five',
    id: 'phone_five',
},
{
    required: true,
    label: 'Email',
    placeholder: 'Email',
    grid: 3,
    type: 'text',
    name: 'email',
    id: 'email',
},
{
    required: true,
    label: 'Email',
    placeholder: 'Email',
    grid: 3,
    type: 'text',
    name: 'email_one',
    id: 'email_one',
}, {
    required: true,
    label: 'Email',
    placeholder: 'Email',
    grid: 3,
    type: 'text',
    name: 'email_two',
    id: 'email_one',
}, {
    required: true,
    label: 'Email',
    placeholder: 'Email',
    grid: 3,
    type: 'text',
    name: 'email_three',
    id: 'email_three',
}, {
    required: true,
    label: 'Email',
    placeholder: 'Email',
    grid: 3,
    type: 'text',
    name: 'email_four',
    id: 'email_four',
}, {
    required: true,
    label: 'Email',
    placeholder: 'Email',
    grid: 3,
    type: 'text',
    name: 'email_five',
    id: 'email_five',
},
{
    required: true,
    label: 'NPI',
    placeholder: 'NPI',
    grid: 4,
    type: 'text',
    name: 'npi',
    id: 'npi',
},
{
    required: true,
    label: 'NPI',
    placeholder: 'NPI',
    grid: 4,
    type: 'text',
    name: 'npi_one',
    id: 'npi_one',
}]

export const InitialPatientCont = [{
    required: true,
    label: 'Staff Name',
    placeholder: 'Staff Name',
    grid: 1,
    menuitems: ['a'],
    type: 'select',
    name: 'staff_name',
    id: 'staff_name',
}, {
    required: true,
    label: 'Callers Work',
    placeholder: 'Callers Work',
    grid: 1,
    type: 'text',
    name: 'callers_work',
    id: 'callers_work',
}, {
    required: true,
    label: 'Date Entered',
    grid: 2,
    type: 'date',
    name: 'date_entered',
    id: 'date_entered',
}, {
    required: true,
    label: 'Callers Cell',
    placeholder: 'Callers Cell',
    grid: 2,
    type: 'text',
    name: 'callers_cell',
    id: 'callers_cell',
}, {
    required: true,
    label: 'Name of Caller',
    placeholder: 'Name of Caller',
    grid: 3,
    type: 'text',
    name: 'name_of_caller',
    id: 'name_of_caller',
}, {
    required: true,
    label: 'Email',
    placeholder: 'Email',
    grid: 3,
    type: 'text',
    name: 'email',
    id: 'email',
}, {
    required: true,
    label: 'Callers Home',
    placeholder: 'Callers Home',
    grid: 4,
    type: 'text',
    name: 'callers_home',
    id: 'callers_home',
}, {
    placeholder: 'Continue',
    grid: 4,
    type: 'button',
}]
export const CallerHeardOne = [{
    required: true,
    label: 'Email',
    placeholder: 'Email',
    grid: 1,
    type: 'select',
    menuitems: ['a'],
    name: 'email',
    id: 'email',
}, {
    required: true,
    label: 'Other (specify)',
    placeholder: 'Other (specify)',
    grid: 2,
    type: 'text',
    name: 'other_specify',
    id: 'other_specify',
}]
export const CallerHeardtwo = [{
    required: true,
    label: 'Referring Provider Name',
    placeholder: 'Referring Provider Name',
    grid: 1,
    type: 'select',
    menuitems: ['a'],
    name: 'referring_provider_name',
    id: 'referring_provider_name',
}, {
    required: true,
    label: 'Referring Provider NPL',
    placeholder: 'Referring Provider NPL',
    grid: 2,
    type: 'text',
    name: 'referring_provider_npl',
    id: 'referring_provider_npl',
}, {
    required: true,
    label: 'Referring Provider Phone',
    placeholder: 'Referring Provider Phone',
    grid: 1,
    type: 'text',
    name: 'referral_provider_phone',
    id: 'referral_provider_phone',
}, {
    required: true,
    label: 'Referring Provider Non NPL',
    placeholder: 'Referring Provider Non NPL',
    grid: 2,
    type: 'text',
    name: 'refer_provider_npl',
    id: 'refer_provider_npl',
}]

export const emergency_contact = [{
    required: true,
    label: 'Emergency Contact#',
    placeholder: 'Emergency Contact#',
    grid: 1,
    type: 'text',
    name: 'emergency_contact',
    id: 'emergency_contact',
}, {
    required: true,
    label: 'Emergency Contact Address',
    placeholder: 'Emergency Contact Address',
    grid: 2,
    type: 'text',
    name: 'emergency_cont_address',
    id: 'emergency_cont_address'
},
{
    required: true,
    label: 'Patients Prefers Confidential Communication Via',
    placeholder: 'Patients Prefers Confidential Communication Via',
    grid: 3,
    type: 'select',
    menuitems: ['ad'],
    name: 'Patients_prefers_confidential_communication_via',
    id: 'Patients_prefers_confidential_communication_via',
}]
export const emergency_contact_one = [{
    required: true,
    label: 'Custodial Parent',
    placeholder: 'Custodial Parent',
    grid: 1,
    type: 'text',
    name: 'custodial_parent',
    id: 'custodial_parent'
}, {
    required: true,
    label: 'Reference Case # CSS#',
    placeholder: 'Reference Case # CSS#',
    grid: 2,
    type: 'text',
    name: 'referenece_case_css',
    id: 'referenece_case_css'
}, {
    required: true,
    label: 'PP#',
    placeholder: 'PP#',
    grid: 3,
    type: 'text',
    name: 'pp',
    id: 'pp'
}, {
    required: true,
    label: 'Referred for Service (s)',
    placeholder: 'Referred for Service (s)',
    grid: 4,
    type: 'text',
    name: 'refer_for_service',
    id: 'refer_for_service',
}]

export const familyContactFirstCollapse = [{
    required: true,
    label: 'Biological Parent Name# 1',
    placeholder: 'Biological Parent Name# 1',
    grid: 1,
    type: 'text',
    name: 'bio_parent_one',
    id: 'bio_parent_one',
}, {
    required: true,
    label: 'Biological Parent Name# 2',
    placeholder: 'Biological Parent Name# 2',
    grid: 1,
    type: 'text',
    name: 'bio_parent_two',
    id: 'bio_parent_two',
}, {
    required: true,
    label: 'Adaptive Parent name #1',
    placeholder: 'Adaptive Parent name #1',
    grid: 1,
    type: 'text',
    name: 'adaptive_parent_one',
    id: 'adaptive_parent_one',
}, {
    required: true,
    label: 'Adaptive Parent name #2',
    placeholder: 'Adaptive Parent name #2',
    grid: 1,
    type: 'text',
    name: 'adaptive_parent_two',
    id: 'adaptive_parent_two',
}, {
    required: true,
    label: 'Spouse Name',
    placeholder: 'Spouse Name',
    grid: 1,
    type: 'text',
    name: 'spousename',
    id: 'spousename',
}, {
    required: true,
    label: 'Mother`s Maiden Name First',
    placeholder: 'Mothers Maiden Name First',
    grid: 1,
    type: 'text',
    name: 'mothermaiden_namefirst',
    id: 'mothermaiden_namefirst',
}, {
    required: true,
    label: 'Phone',
    placeholder: 'Phone',
    grid: 2,
    type: 'text',
    name: 'phone',
    id: 'phone',
},
{
    required: true,
    label: 'Phone',
    placeholder: 'Phone',
    grid: 2,
    type: 'text',
    name: 'phone_one',
    id: 'phone_one',
}, {
    required: true,
    label: 'Phone',
    placeholder: 'Phone',
    grid: 2,
    type: 'text',
    name: 'phone_two',
    id: 'phone_two',
}, {
    required: true,
    label: 'Phone',
    placeholder: 'Phone',
    grid: 2,
    type: 'text',
    name: 'phone_three',
    id: 'phone_three',
}, {
    required: true,
    label: 'Phone',
    placeholder: 'Phone',
    grid: 2,
    type: 'text',
    name: 'phone_four',
    id: 'phone_four',
}, {
    required: true,
    label: 'Mother`s Maiden Name Last',
    placeholder: 'Mother`s Maiden Name Last',
    grid: 2,
    type: 'text',
    name: 'mothermaiden_namelast',
    id: 'mothermaiden_namelast',
}, {
    required: true,
    label: 'Email',
    placeholder: 'Email',
    grid: 3,
    type: 'text',
    name: 'email',
    id: 'email',
},
{
    required: true,
    label: 'Email',
    placeholder: 'Email',
    grid: 3,
    type: 'text',
    name: 'email_one',
    id: 'email_one',
}, {
    required: true,
    label: 'Email',
    placeholder: 'Email',
    grid: 3,
    type: 'text',
    name: 'email_two',
    id: 'email_one',
}, {
    required: true,
    label: 'Email',
    placeholder: 'Email',
    grid: 3,
    type: 'text',
    name: 'email_three',
    id: 'email_three',
}, {
    required: true,
    label: 'Email',
    placeholder: 'Email',
    grid: 3,
    type: 'text',
    name: 'email_four',
    id: 'email_four',
}]


export const familyContactsecondCollapse = [{
    required: true,
    label: 'Step Parent Name# 1',
    placeholder: 'Step Parent Name# 1',
    grid: 1,
    type: 'text',
    name: 'step_parent_one',
    id: 'step_parent_one',
}, {
    required: true,
    label: 'Step Parent Name# 2',
    placeholder: 'Step Parent Name# 2',
    grid: 1,
    type: 'text',
    name: 'step_parent_two',
    id: 'step_parent_two',
}, {
    required: true,
    label: 'Foster Parent name #1',
    placeholder: 'Foster Parent name #1',
    grid: 1,
    type: 'text',
    name: 'foster_parent_one',
    id: 'foster_parent_one',
}, {
    required: true,
    label: 'Foster Parent name #2',
    placeholder: 'Foster Parent name #2',
    grid: 1,
    type: 'text',
    name: 'foster_parent_two',
    id: 'foster_parent_two',
}, {
    required: true,
    label: 'Guardian Name #1',
    placeholder: 'Guardian Name #1',
    grid: 1,
    type: 'text',
    name: 'guardian_name_one',
    id: 'guardian_name_one',
}, {
    required: true,
    label: 'Guardian Name #2',
    placeholder: 'Guardian Name #2',
    grid: 1,
    type: 'text',
    name: 'guardian_name_two',
    id: 'guardian_name_two',
}, {
    required: true,
    label: 'Phone',
    placeholder: 'Phone',
    grid: 2,
    type: 'text',
    name: 'phone',
    id: 'phone',
},
{
    required: true,
    label: 'Phone',
    placeholder: 'Phone',
    grid: 2,
    type: 'text',
    name: 'phone_one',
    id: 'phone_one',
}, {
    required: true,
    label: 'Phone',
    placeholder: 'Phone',
    grid: 2,
    type: 'text',
    name: 'phone_two',
    id: 'phone_two',
}, {
    required: true,
    label: 'Phone',
    placeholder: 'Phone',
    grid: 2,
    type: 'text',
    name: 'phone_three',
    id: 'phone_three',
}, {
    required: true,
    label: 'Phone',
    placeholder: 'Phone',
    grid: 2,
    type: 'text',
    name: 'phone_four',
    id: 'phone_four',
}, {
    required: true,
    label: 'Phone',
    placeholder: 'Phone',
    grid: 2,
    type: 'text',
    name: 'phone_five',
    id: 'phone_five',
}, {
    required: true,
    label: 'Email',
    placeholder: 'Email',
    grid: 3,
    type: 'text',
    name: 'email',
    id: 'email',
},
{
    required: true,
    label: 'Email',
    placeholder: 'Email',
    grid: 3,
    type: 'text',
    name: 'email_one',
    id: 'email_one',
}, {
    required: true,
    label: 'Email',
    placeholder: 'Email',
    grid: 3,
    type: 'text',
    name: 'email_two',
    id: 'email_one',
}, {
    required: true,
    label: 'Email',
    placeholder: 'Email',
    grid: 3,
    type: 'text',
    name: 'email_three',
    id: 'email_three',
}, {
    required: true,
    label: 'Email',
    placeholder: 'Email',
    grid: 3,
    type: 'text',
    name: 'email_four',
    id: 'email_four',
},
{
    required: true,
    label: 'Email',
    placeholder: 'Email',
    grid: 3,
    type: 'text',
    name: 'email_five',
    id: 'email_five',
}]

//label, bold, radio, text, button, empty
export const guardianone = [{
    placeholder: 'To set Guarantor 1 information, either',
    grid: 1,
    type: 'label',
},
{
    placeholder: 'Family Contacts',
    grid: 1,
    type: 'bold',
},
{
    label: "",
    required: true,
    id: "biological_radios",
    type: "radio",
    grid: 1,
    name: "biological_radios",
    radios: ['Biological Parent 1', 'Biological Parent 1']
},
{
    label: "",
    required: true,
    id: "guardian_radios",
    type: "radio",
    grid: 1,
    name: "guardian_radios",
    radios: ['Guardian 1', 'Guardian 2']
},
{
    required: true,
    label: 'Name',
    placeholder: 'Name',
    grid: 1,
    type: 'text',
    name: 'name',
    id: 'name',
}, {
    required: true,
    label: 'ZIP',
    placeholder: 'ZIP',
    grid: 1,
    type: 'text',
    name: 'zip',
    id: 'zip',
}, {
    required: true,
    label: 'Email',
    placeholder: 'Email',
    grid: 1,
    type: 'text',
    name: 'email',
    id: 'email',
},
{
    placeholder: 'Use Patient Info',
    grid: 2,
    type: 'button'
}, {
    label: "",
    type: "empty",
    grid: 2,
}, {
    label: "",
    required: true,
    id: "adaptiveradios",
    type: "radio",
    grid: 2,
    name: "adaptiveradios",
    radios: ['Adoptive Parent 1', 'Adoptive Parent 2']
},
{
    label: "",
    type: "empty",
    grid: 2,
},
{
    type: 'text',
    required: true,
    label: 'Address',
    placeholder: 'Address',
    grid: 2,
    name: 'address',
    id: 'address',
}, {
    type: 'text',
    grid: 2,
    required: true,
    label: 'OR',
    placeholder: 'OR',
    name: 'or',
    id: 'or',
},
{
    label: "",
    type: "empty",
    grid: 2,
},
{
    placeholder: 'or first select a family contact & then',
    grid: 3,
    type: 'label',
},
{
    label: "",
    type: "empty",
    grid: 3,
},
{
    label: "",
    required: true,
    id: "stepparentradios",
    type: "radio",
    grid: 3,
    name: "stepparentradios",
    radios: ['Step Parent 1', 'Step Parent 2']
},
{
    label: "",
    type: "empty",
    grid: 3,
},
{
    type: 'text',
    grid: 3,
    required: true,
    label: 'City',
    placeholder: 'City',
    name: 'city',
    id: 'city',
}, {
    type: 'text',
    grid: 3,
    required: true,
    label: 'Phone',
    placeholder: 'Phone',
    name: 'phone',
    id: 'phone',
}, {
    label: "",
    type: "empty",
    grid: 3,
},
{
    placeholder: 'Use Patient Info',
    grid: 4,
    type: 'button'
}, {
    label: "",
    type: "empty",
    grid: 4,
},
{
    label: "",
    required: true,
    id: "foster_Parent1",
    type: "radio",
    grid: 4,
    name: "foster_Parent1",
    radios: ['Foster Parent 1', 'Foster Parent 2']
}, {
    label: "",
    type: "empty",
    grid: 4,
},
{
    type: 'text',
    grid: 4,
    required: true,
    label: 'State',
    placeholder: 'State',
    name: 'state',
    id: 'state',
}, {
    type: 'text',
    grid: 4,
    required: true,
    label: 'SSN',
    placeholder: 'SSN',
    name: 'ssn',
    id: 'ssn',
},
{
    placeholder: 'Continue',
    grid: 4,
    type: 'button'
},
]

export const guardiantwo = [{
    placeholder: 'To set Guarantor 1 information, either',
    grid: 1,
    type: 'label',
},
{
    placeholder: 'Family Contacts',
    grid: 1,
    type: 'bold',
},
{
    label: "",
    required: true,
    id: "biological_radios",
    type: "radio",
    grid: 1,
    name: "biological_radios",
    radios: ['Biological Parent 1', 'Biological Parent 1']
},
{
    label: "",
    required: true,
    id: "guardian_radios",
    type: "radio",
    grid: 1,
    name: "guardian_radios",
    radios: ['Guardian 1', 'Guardian 2']
},
{
    required: true,
    label: 'Name',
    placeholder: 'Name',
    grid: 1,
    type: 'text',
    name: 'name',
    id: 'name',
}, {
    required: true,
    label: 'ZIP',
    placeholder: 'ZIP',
    grid: 1,
    type: 'text',
    name: 'zip',
    id: 'zip',
}, {
    required: true,
    label: 'Email',
    placeholder: 'Email',
    grid: 1,
    type: 'text',
    name: 'email',
    id: 'email',
},
{
    placeholder: 'Use Patient Info',
    grid: 2,
    type: 'button'
}, {
    label: "",
    type: "empty",
    grid: 2,
}, {
    label: "",
    required: true,
    id: "adaptiveradios",
    type: "radio",
    grid: 2,
    name: "adaptiveradios",
    radios: ['Adoptive Parent 1', 'Adoptive Parent 2']
},
{
    label: "",
    type: "empty",
    grid: 2,
},
{
    type: 'text',
    required: true,
    label: 'Address',
    placeholder: 'Address',
    grid: 2,
    name: 'address',
    id: 'address',
}, {
    type: 'text',
    grid: 2,
    required: true,
    label: 'OR',
    placeholder: 'OR',
    name: 'or',
    id: 'or',
},
{
    label: "",
    type: "empty",
    grid: 2,
},
{
    placeholder: 'or first select a family contact & then',
    grid: 3,
    type: 'label',
},
{
    label: "",
    required: true,
    id: "stepparentradios",
    type: "radio",
    grid: 3,
    name: "stepparentradios",
    radios: ['Step Parent 1', 'Step Parent 2']
},
{
    label: "",
    type: "empty",
    grid: 3,
},
{
    type: 'text',
    grid: 3,
    required: true,
    label: 'City',
    placeholder: 'City',
    name: 'city',
    id: 'city',
}, {
    type: 'text',
    grid: 3,
    required: true,
    label: 'Phone',
    placeholder: 'Phone',
    name: 'phone',
    id: 'phone',
}, {
    label: "",
    type: "empty",
    grid: 3,
},
{
    placeholder: 'Use Patient Info',
    grid: 4,
    type: 'button'
}, {
    label: "",
    type: "empty",
    grid: 4,
},
{
    label: "",
    required: true,
    id: "foster_Parent1",
    type: "radio",
    grid: 4,
    name: "foster_Parent1",
    radios: ['Foster Parent 1', 'Foster Parent 2']
}, {
    label: "",
    type: "empty",
    grid: 4,
},
{
    type: 'text',
    grid: 4,
    required: true,
    label: 'State',
    placeholder: 'State',
    name: 'state',
    id: 'state',
}, {
    type: 'text',
    grid: 4,
    required: true,
    label: 'SSN',
    placeholder: 'SSN',
    name: 'ssn',
    id: 'ssn',
},
{
    placeholder: 'Continue',
    grid: 4,
    type: 'button'
}]

export const responsibleperson = [{
    type: 'text',
    grid: 1,
    required: true,
    label: 'RelationShip',
    placeholder: 'RelationShip',
    name: 'relationship',
    id: 'relationship',
}, {
    type: 'text',
    grid: 1,
    required: true,
    label: 'City',
    placeholder: 'City',
    name: 'city',
    id: 'city',
}, {
    type: 'text',
    grid: 2,
    required: true,
    label: 'First Name',
    placeholder: 'First Name',
    name: 'first_name',
    id: 'first_name',
}, {
    type: 'text',
    grid: 2,
    required: true,
    label: 'State',
    placeholder: 'State',
    name: 'state',
    id: 'state'
}, {
    type: 'text',
    grid: 3,
    required: true,
    label: 'Last Name',
    placeholder: 'Last Name',
    name: 'last_name',
    id: 'last_name',
}, {
    type: 'text',
    grid: 3,
    required: true,
    label: 'Zip',
    placeholder: 'Zip',
    name: 'zip',
    id: 'zip',
}, {
    type: 'text',
    grid: 4,
    required: true,
    label: 'Phone/Email',
    placeholder: 'Phone/Email',
    name: 'phone_email',
    id: 'phone_email',
}, {
    type: 'text',
    grid: 4,
    required: true,
    label: 'Country',
    placeholder: 'Country',
    name: 'country',
    id: 'country'
}]

export const customcontact = [{
    type: 'text',
    required: true,
    placeholder: 'Role',
    name: 'role',
    id: 'role'
}, {
    type: 'text',
    required: true,
    placeholder: 'Name',
    name: 'name',
    id: 'name'
}, {
    type: 'text',
    required: true,
    placeholder: 'Phone',
    name: 'phone',
    id: 'phone'
}, {
    type: 'text',
    required: true,
    placeholder: 'Fax',
    name: 'fax',
    id: 'fax'
}, {
    type: 'text',
    required: true,
    placeholder: 'Email',
    name: 'email',
    id: 'email'
}, {
    type: 'button',
    required: true,
    placeholder: 'Add',
}]

export const TelephoneIntake = [{
    type: 'select',
    required: true,
    placeholder: 'Staff Name',
    menuitems: ['a'],
    label: 'Staff Name',
    name: 'staff_name',
    id: 'staff_name'
}, {
    type: 'date',
    required: true,
    label: 'Date Entered',
    placeholder: 'Date Entered',
    name: 'date_entered',
    id: 'date_entered'
}, {
    type: 'text',
    required: true,
    placeholder: 'Contact Via',
    label: 'Contact Via',
    name: 'contact_via',
    id: 'contact_via'
}, {
    type: 'button',
    required: true,
    placeholder: 'Continue',
}]

export const about_prospective = [{
    type: 'text',
    required: true,
    placeholder: 'First Name',
    label: 'First Name',
    name: 'first_name',
    id: 'first_name',
    grid: 1
}, {
    type: 'text',
    required: true,
    placeholder: 'Age',
    label: 'Age',
    name: 'age',
    id: 'age',
    grid: 1
}, {
    type: 'text',
    grid: 1,
    required: true,
    placeholder: 'Unique Patient ID',
    label: 'Unique Patient ID',
    name: 'unique_patient_id',
    id: 'unique_patient_id',
}, {
    type: 'text',
    required: true,
    placeholder: 'Middle',
    label: 'Middle',
    name: 'middle',
    id: 'middle',
    grid: 2
}, {
    type: 'select',
    grid: 2,
    required: true,
    menuitems: ['a'],
    placeholder: 'Gender',
    label: 'Gender',
    name: 'gender',
    id: 'gender'
}, {
    type: 'button',
    placeholder: 'Generate ID#',
    grid: 2
}, {
    type: 'text',
    required: true,
    placeholder: 'last',
    label: 'Last',
    name: 'last',
    id: 'last',
    grid: 3
}, {
    type: 'text',
    required: true,
    placeholder: 'Refer to Patient as',
    label: 'Refer to Patient as',
    name: 'refer_to_patient',
    id: 'refer_to_patient',
    grid: 3
}, {
    type: 'button',
    placeholder: 'Continue',
    grid: 3
}, {
    type: 'date',
    required: true,
    placeholder: 'DOB',
    label: 'DOB',
    name: 'dob',
    id: 'dob',
    grid: 4
}, {
    type: 'text',
    required: true,
    grid: 4,
    placeholder: 'SSN',
    label: 'SSN',
    name: 'ssn',
    id: 'ssn'
}]

export const aboutcaller = [{
    type: 'text',
    required: true,
    grid: 1,
    placeholder: 'Name of Caller',
    label: 'Name of Caller',
    name: 'name_of_caller',
    id: 'name_of_caller',
}, {
    type: 'text',
    required: true,
    grid: 1,
    placeholder: 'Cell',
    label: 'Cell',
    name: 'cell',
    id: 'cell',
},
{
    type: 'text',
    required: true,
    grid: 2,
    placeholder: 'Caller`s Email',
    label: 'Caller`s Email',
    name: 'callers_email',
    id: 'callers_email',
}, {
    type: 'text',
    required: true,
    grid: 2,
    placeholder: 'Relationship to Parent',
    label: 'Relationship to Parent',
    name: 'relationship_to_parent',
    id: 'relationship_to_parent',
},
{
    type: 'text',
    required: true,
    grid: 3,
    placeholder: 'Home',
    label: 'Home',
    name: 'home',
    id: 'home',
}, {
    type: 'date',
    required: true,
    grid: 4,
    label: 'Work',
    name: 'work',
    id: 'work',
}]
export const aboutcallertwo = [{
    type: 'select',
    menuitems: ['a'],
    required: true,
    grid: 1,
    label: 'Referral Type',
    name: 'referral_type',
    id: 'referral_type',
}, {
    type: 'text',
    required: true,
    grid: 2,
    placeholder: 'Other (specify)',
    label: 'Other (specify)',
    name: 'other_specify',
    id: 'other_specify',
}, {
    type: 'button',
    grid: 3,
    placeholder: 'Continue',
}, {
    label: '',
    grid: 4,
    type: 'empty',
}]


export const notes = [{
    type: 'textarea',
    required: true,
    grid: 1,
    placeholder: 'Additional Notes',
    label: 'Additional Notes',
    name: 'addiotnial_notes',
    id: 'addiotnial_notes',
}, {
    type: 'textarea',
    required: true,
    grid: 1,
    placeholder: 'Patient Calender Notes',
    label: 'Patient Calender Notes',
    name: 'patient_calender_notes',
    id: 'patient_calender_notes',
}, {
    type: 'textarea',
    required: true,
    grid: 2,
    placeholder: 'Other Agencies Involved',
    label: 'Other Agencies Involved',
    name: 'other_agencies',
    id: 'other_agencies',
}, {
    type: 'textarea',
    required: true,
    grid: 2,
    placeholder: 'Miscalleneaous Notes',
    label: 'Miscalleneaous Notes',
    name: 'miscalleneous_notes',
    id: 'miscalleneous_notes',
},]