// const rows = [
//   {
//     nop: "Abcd",
//     phone_no_practice: "090078601",
//     eocp: "provider@clinidoc.com",
//     reason_for_referral: "Lorem ipsum",
//     patient_name: "Jack Jones",
//     best_time_for_contact: "24-06-2021 12:35 A.M",
//     patient_phone: "090078601",
//     assign_by: "Receptionist",
//     email: "patient@clinidoc.com",
//     referral_type_id: "Provider",
//     activeColor: "green",
//   },
//   {
//     nop: "Abcd",
//     phone_no_practice: "090078601",
//     eocp: "provider@clinidoc.com",
//     reason_for_referral: "Lorem ipsum dolor sit",
//     patient_name: "Jack Jones",
//     best_time_for_contact: "24-06-2021 12:35 A.M",
//     patient_phone: "090078601",
//     assign_by: "Receptionist",
//     email: "patient@clinidoc.com",
//     referral_type_id: "Provider",
//     activeColor: "green",
//   },
//   {
//     nop: "Abcd",
//     phone_no_practice: "090078601",
//     eocp: "provider@clinidoc.com",
//     reason_for_referral: "Lorem ipsum dolor sit",
//     patient_name: "Jack Jones",
//     best_time_for_contact: "24-06-2021 12:35 A.M",
//     patient_phone: "090078601",
//     assign_by: "Receptionist",
//     email: "patient@clinidoc.com",
//     referral_type_id: "Provider",
//     activeColor: "#F3AA07",
//   },
//   {
//     nop: "Abcd",
//     pnop: "090078601",
//     eocp: "provider@clinidoc.com",
//     reason_for_referral: "Lorem ipsum dolor sit",
//     patient_name: "Jack Jones",
//     best_time_for_contact: "24-06-2021 12:35 A.M",
//     patient_phone: "090078601",
//     assign_by: "Receptionist",
//     email: "patient@clinidoc.com",
//     referral_type_id: "Provider",
//     activeColor: "#F3AA07",
//   },
//   {
//     nop: "Abcd",
//     pnop: "090078601",
//     eocp: "provider@clinidoc.com",
//     reason_for_referral: "Lorem ipsum dolor sit",
//     patient_name: "Jack Jones",
//     best_time_for_contact: "24-06-2021 12:35 A.M",
//     patient_phone: "090078601",
//     assign_by: "Receptionist",
//     email: "patient@clinidoc.com",
//     referral_type_id: "Provider",
//     activeColor: "blue",
//   },
// ];
